/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package countryinfo;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import org.oorsprong.websamples.ArrayOftContinent;
import org.oorsprong.websamples.ArrayOftCountryCodeAndName;
import org.oorsprong.websamples.ArrayOftCountryCodeAndNameGroupedByContinent;
import org.oorsprong.websamples.ArrayOftCurrency;
import org.oorsprong.websamples.TContinent;
import org.oorsprong.websamples.TCountryCodeAndName;
import org.oorsprong.websamples.TCountryCodeAndNameGroupedByContinent;
import org.oorsprong.websamples.TCountryInfo;
import org.oorsprong.websamples.TCurrency;
import org.oorsprong.websamples.TLanguage;

/**
 *
 * @author Sandalu
 */
public class CountryApp extends javax.swing.JFrame {

    /**
     * Creates new form CountryApp
     */
    public CountryApp() {
        initComponents();
        ArrayOftContinent con=listOfContinentsByName();
        List<TContinent> tcon=con.getTContinent();
        continentcombo.addItem("Select Continent");
        for(TContinent s:tcon){
            String stt=s.getSName();
//            lisstr.add(str);
                continentcombo.addItem(stt);
        }
        
        boxcode.setBackground(new Color(0,0,0,10));
        boxcurrency.setBackground(new Color(0,0,0,10));
        boxlanguage.setBackground(new Color(0,0,0,10));
        boxcapital.setBackground(new Color(0,0,0,10));
        boxphone.setBackground(new Color(0,0,0,10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boxcode = new javax.swing.JTextField();
        boxcurrency = new javax.swing.JTextField();
        continentcombo = new javax.swing.JComboBox<>();
        countrycombo = new javax.swing.JComboBox<>();
        boxcapital = new javax.swing.JTextField();
        boxphone = new javax.swing.JTextField();
        boxlanguage = new javax.swing.JTextField();
        boxflag = new javax.swing.JLabel();
        searchlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(boxcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 280, 30));

        boxcurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxcurrencyActionPerformed(evt);
            }
        });
        jPanel1.add(boxcurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 280, 30));

        continentcombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                continentcomboItemStateChanged(evt);
            }
        });
        continentcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continentcomboActionPerformed(evt);
            }
        });
        jPanel1.add(continentcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 180, 30));

        jPanel1.add(countrycombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 180, 30));
        jPanel1.add(boxcapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 280, 30));
        jPanel1.add(boxphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, 280, 30));
        jPanel1.add(boxlanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, 280, 30));
        jPanel1.add(boxflag, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 270, 180));

        searchlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchlblMouseClicked(evt);
            }
        });
        jPanel1.add(searchlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 170, 60));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sandalu\\Documents\\NetBeansProjects\\CountryInfo\\images\\back5.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 830, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void continentcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continentcomboActionPerformed
        ArrayOftCountryCodeAndNameGroupedByContinent contcon=listOfCountryNamesGroupedByContinent();
        List<TCountryCodeAndNameGroupedByContinent> co=contcon.getTCountryCodeAndNameGroupedByContinent();
        String x=(String)continentcombo.getSelectedItem();
        countrycombo.addItem("Select Country");
        for(TCountryCodeAndNameGroupedByContinent p:co){
            TContinent y=p.getContinent();
            String v=y.getSName();
                ArrayOftCountryCodeAndName sd=p.getCountryCodeAndNames();
                List<TCountryCodeAndName> po=sd.getTCountryCodeAndName();
                for(TCountryCodeAndName fg:po){
                String cou=fg.getSName();
                countrycombo.addItem(cou);
                }
        }
    }//GEN-LAST:event_continentcomboActionPerformed

    private void continentcomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_continentcomboItemStateChanged

    }//GEN-LAST:event_continentcomboItemStateChanged

    private void boxcurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxcurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxcurrencyActionPerformed

    private void searchlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlblMouseClicked
        boxcode.setText(countryISOCode((String)countrycombo.getSelectedItem()));
        TCurrency t=countryCurrency(boxcode.getText());
        boxcurrency.setText(t.getSName()); 
        boxcapital.setText(capitalCity(boxcode.getText()));
        boxphone.setText(countryIntPhoneCode(boxcode.getText()));
        
//        TLanguage tl=new TLanguage();
//        String sc=tl.getSISOCode();
        boxlanguage.setText(languageName(boxcode.getText()));
//        boxlcode.setText(languageISOCode(boxlanguage.getText()));

        
         Image image=null;
         try{
             URL url=new URL(countryFlag(boxcode.getText()));
             image=ImageIO.read(url);
         } catch (Exception ex) {
            Logger.getLogger(CountryApp.class.getName()).log(Level.SEVERE, null, ex);
        }
          boxflag.setIcon(new javax.swing.ImageIcon(image));
    }//GEN-LAST:event_searchlblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountryApp().setVisible(true);
            }
        });
        
        
    }

    private static String countryISOCode(java.lang.String sCountryName) {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.countryISOCode(sCountryName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxcapital;
    private javax.swing.JTextField boxcode;
    private javax.swing.JTextField boxcurrency;
    private javax.swing.JLabel boxflag;
    private javax.swing.JTextField boxlanguage;
    private javax.swing.JTextField boxphone;
    private javax.swing.JComboBox<String> continentcombo;
    private javax.swing.JComboBox<String> countrycombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel searchlbl;
    // End of variables declaration//GEN-END:variables

    private static String currencyName(java.lang.String sCurrencyISOCode) {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.currencyName(sCurrencyISOCode);
    }

    private static TCurrency countryCurrency(java.lang.String sCountryISOCode) {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.countryCurrency(sCountryISOCode);
    }

    private static ArrayOftCountryCodeAndNameGroupedByContinent listOfCountryNamesGroupedByContinent() {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.listOfCountryNamesGroupedByContinent();
    }

    private static ArrayOftCurrency listOfCurrenciesByName() {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.listOfCurrenciesByName();
    }

    private static ArrayOftCurrency listOfCurrenciesByCode() {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.listOfCurrenciesByCode();
    }

    private static ArrayOftContinent listOfContinentsByName() {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.listOfContinentsByName();
    }

    private static String capitalCity(java.lang.String sCountryISOCode) {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.capitalCity(sCountryISOCode);
    }

    private static String countryIntPhoneCode(java.lang.String sCountryISOCode) {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.countryIntPhoneCode(sCountryISOCode);
    }

    private static String languageName(java.lang.String sISOCode) {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.languageName(sISOCode);
    }

    private static String languageISOCode(java.lang.String sLanguageName) {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.languageISOCode(sLanguageName);
    }

    private static String countryFlag(java.lang.String sCountryISOCode) {
        org.oorsprong.websamples.CountryInfoService service = new org.oorsprong.websamples.CountryInfoService();
        org.oorsprong.websamples.CountryInfoServiceSoapType port = service.getCountryInfoServiceSoap();
        return port.countryFlag(sCountryISOCode);
    }

    

    
}
